"""Add password expiration fields

Revision ID: b59ad4048b35
Revises: 
Create Date: 2025-06-26 20:19:06.743980

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59ad4048b35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns without server_default for SQLite compatibility
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET password_changed_at = :now, 
            force_password_change = :force_change
        WHERE password_changed_at IS NULL
    """), {
        'now': datetime.utcnow(),
        'force_change': False
    })
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'password_expires_at')
    op.drop_column('users', 'password_changed_at')
    # ### end Alembic commands ###
